In [1]:
import numpy as np

In [2]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [4]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [37]:
a = np.eye(4, 5)
print(a)
print()
print(a[[0,3]])
print()
a[[0,3],[1,3]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]



array([0., 1.])

In [28]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x[:,np.newaxis,:,:]

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]]])

In [38]:
np.linalg.det(np.eye(3,3))

1.0

In [39]:
np.linalg.eig(np.eye(3,3))

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [41]:
a = np.array([[1,1], [1,2]])
a * a.transpose()

array([[1, 1],
       [1, 4]])

In [42]:
b = np.eye(2)
b * b.transpose()

array([[1., 0.],
       [0., 1.]])

In [43]:
np.array()

TypeError: array() missing required argument 'object' (pos 1)